### ISSUE TITLE
Question:  is the only accessMode ReadWriteOnce?

### ISSUE THREAD

**Issue by SimonHeimberg** [cloudscale-ch/csi-cloudscale#14]
### What did you do? (required.)

I read [README.md](https://github.com/cloudscale-ch/csi-cloudscale/blob/58ac8e07f325/README.md) and all examples in [examples/kubernetes](https://github.com/cloudscale-ch/csi-cloudscale/tree/58ac8e07f325/examples/kubernetes) (and [post in tech insight and news](https://www.cloudscale.ch/en/news/2019/03/15/persistent-volumes-in-kubernetes-with-csi).

### What did you expect to happen?

In all examples, there is `accessModes: ReadWriteOnce`. Does this mean this is the only supported value? Or is ReadWriteMany also supported. I miss a clear statement.

* csi-cloudscale version: 1.0.1 58ac8e07f325

**Comment by davidhalter** [comment]
Hi Simon 

"ReadWriteOnce" is currently the only supported value. We might look into "ReadWriteMany" in the future; however, this would only work in very specific setups, as most filesystems like ext4 do not support concurrent r/w access. If concurrent r/w access from multiple pods is a must, you might want to have a look at GlusterFS or a similar distributed filesystem, even though there is some (storage) overhead.

**Comment by SimonHeimberg** [comment]
Of course, the file system would also have to support it. Seems I had forgotten that it is a disc.

Thank you
