### ISSUE TITLE
Support Kubernetes 1.12+

### ISSUE THREAD

**Issue by tobru** [cloudscale-ch/csi-cloudscale#2]
### What did you do? (required. The issue will be **closed** when not provided.)

Installed csi-cloudscale on Kubernetes 1.12

### What did you expect to happen?

It just works

* CSI Version: dev
* Kubernetes Version: 1.12
* Cloud provider/framework version, if applicable (such as Rancher): Rancher

See also digitalocean/csi-digitalocean/issues/86

**Comment by davidhalter** [comment]
@tobru 

I think I fixed it. Please test again. I didn't test against rancher, but against a simple Kubernetes 1.12.1 cluster. Let me know if something is still broken.

**Comment by tobru** [comment]
I can confirm that it works now with Kubernets 1.12
