### ISSUE TITLE
Feature: Implement NodeGetVolumeStats

### ISSUE THREAD

**Issue by splattner** [cloudscale-ch/csi-cloudscale#20]
It would be nice to implement NodeGetVolumeStats https://github.com/cloudscale-ch/csi-cloudscale/blob/097416d8cd32708abbaa7607e1459ae561fdeac9/driver/node.go#L355 to have some metrics for the PV/PVC  which then can be monitored.

**Comment by davidhalter** [comment]
Hey @splattner 

I have created an internal ticket for this. We will evaluate when and if we do it.

However, It is unlikely that we have time for this in the next two months. Is this OK for you?

~ Dave

**Comment by splattner** [comment]
awesome!
We currently have no good solution to monitor our PVC/PV on the Kubernetes Cluster and therefore this feature would be great.
But no hurry! And as its OpenSource, maybee someone else finds time to implement this :)
thx

**Comment by megian** [comment]
Haven't been aware of that we don't get stats from the CSI driver, we had now workload where the disks went full, which caused production workload went down. 

Possibly digitalocean/csi-digitalocean#197 might be a reference.
