### ISSUE TITLE
Support volume resize

### ISSUE THREAD

**Issue by tobru** [cloudscale-ch/csi-cloudscale#3]
### What did you do? (required. The issue will be **closed** when not provided.)

Tried to change size of a PVC.

### What did you expect to happen?

Volume get's resized.

* CSI Version: dev
* Kubernetes Version: 1.11
* Cloud provider/framework version, if applicable (such as Rancher): Rancher

Error logged when PVC gets edited:

```
error: persistentvolumeclaims "csi-pvc1" could not be patched: persistentvolumeclaims "csi-pvc1" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize

```

**Comment by davidhalter** [comment]
Resizing PVC's is currently not part of the CSI spec (see https://github.com/container-storage-interface/spec/blob/v0.3.0/spec.md). There are a number of tickets in the CSI spec issue tracker that try to make resizing part of the spec. Note that Kubernetes support for this would also needed to be done for that. I suppose we are speaking of 3+ months at least.

https://github.com/container-storage-interface/spec/issues/212
https://github.com/container-storage-interface/spec/pull/222

I will close this ticket and wait until it's supported in Kubernetes & the CSI spec.

**Comment by srueg** [comment]
The volume expansion made it to the spec, any plans to implement it? https://kubernetes-csi.github.io/docs/volume-expansion.html

**Comment by davidhalter** [comment]
We currently don't have plans for this, but we will discuss it internally.

**Comment by alakae** [comment]
Feature is available in latest release.
