### ISSUE TITLE
CSI not working with Ubuntu Nodes (Rancher)

### ISSUE THREAD

**Issue by davidhalter** [cloudscale-ch/csi-cloudscale#9]
### What did you do? (required. The issue will be **closed** when not provided.)

Created a Rancher cluster with Ubuntu Nodes and created a PVC with rancher.

### What did you expect to happen?

Everything should have worked.

### Issue

This is a udev issue, documented here: https://bugs.launchpad.net/ubuntu/+source/udev/+bug/1838992

**Comment by ferdinandhuebner** [comment]
I think we might have the same problem on CoreOS Container Linux and I see the following error messages: 

```
MountVolume.MountDevice failed for volume "pvc-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx": 
rpc error: code = Internal desc = cryptsetup luksFormat failed: 
exit status 4 
cmd: 
'cryptsetup -v --batch-mode --cipher aes-xts-plain64 --key-size 512 --key-file /tmp/luks-389888550 luksFormat /dev/disk/by-id/scsi-xxxxxxxx-xxxx-xxxx-x' 
output: "Device /dev/disk/by-id/scsi-xxxxxxxx-xxxx-xxxx-x doesn't exist or access denied.
Command failed with code 15: Block device required
```

It usually works when I detach and re-attach the PVC (e.g. by scaling down a deployment or stateful set on kubernetes).

In the bug-report you mentioned that `udevadm trigger` fixes the `/dev/disk/by-id` entry. Can we work around this issue by calling `udevadm trigger` in the csi-plugin if we detect this bug?

**Comment by davidhalter** [comment]
> In the bug-report you mentioned that udevadm trigger fixes the /dev/disk/by-id entry. Can we work around this issue by calling udevadm trigger in the csi-plugin if we detect this bug?

I think this is probably a good idea. I was considering just using `udevadm trigger` generally (even if there is no bug).

My only reservation is that I'm just not sure about possible side effects. I'm not an expert at all when it comes to udev.

I would potentially have time to work on this in the beginning/middle of November. Is this early enough for you?

**Comment by ferdinandhuebner** [comment]
> I think this is probably a good idea. I was considering just using `udevadm trigger` generally (even if there is no bug).
> 
> My only reservation is that I'm just not sure about possible side effects. I'm not an expert at all when it comes to udev.

We could copy the behaviour of the openstack cloud-provider that runs some extra code during cinder volume attachment, take a look at [probeAttachedVolume in cinder_util.go](https://github.com/kubernetes/cloud-provider-openstack/blob/v1.16.0/pkg/volume/cinder/cinder_util.go): After the disk is attached with the cinder API, they rescan the SCSI bus and call `udevadm settle` which waits until all events in the udev event queue are handled. If we do this during `NodeStageVolume`, this might already be already enough to fix this bug which looks a bit like a timing issue. 

> 
> I would potentially have time to work on this in the beginning/middle of November. Is this early enough for you?

Of course, that would be soon enough. This bug isn't very severe for us.

**Comment by davidhalter** [comment]
Just a heads up: We are discussing what we want to do here next Monday

**Comment by davidhalter** [comment]
FYI I have started working on this.

**Comment by davidhalter** [comment]
v1.0.1 has been released.
